export const info = [
  {
    id: 1,
    about: {
      familierTechnologies:
        "Next JS | React JS | Express JS | Node JS | Full Stack Developer | Front End Developer | Software Engineer ",
      summary:
        "Skilled and motivated React JS/Full Stack Developer with two years of experience in designing, developing and deploying web applications/mobile applications.",
    },
    qualification: {
      degree: "Master",
      university: "Virtual University of Pakistan",
      subjects: "Computer Science",
      year: "March, 2018 - April, 2020",
      cgpa: "3.34",
    },
    skills: [
      { id: 1, name: "AJAX" },
      { id: 2, name: "Agile Development" },
      { id: 3, name: "Agile Software Development" },
      { id: 4, name: "Algorithm Design" },
      { id: 5, name: "Back-End Web Development" },
      { id: 6, name: "Bootstrap" },
      { id: 7, name: "C++" },
      { id: 8, name: "Cascading Style Sheets (CSS)" },
      { id: 9, name: "Computer Science" },
      { id: 10, name: "Data Structures" },
      { id: 11, name: "Debugging" },
      { id: 12, name: "Express.js" },
      { id: 13, name: "Front-End Design" },
      { id: 14, name: "Git" },
      { id: 15, name: "HTML" },
      { id: 16, name: "HTML5" },
      { id: 17, name: "JSON" },
      { id: 18, name: "Material-UI" },
      { id: 19, name: "MERN Stack" },
      { id: 20, name: "Mern Stack Bootcamp" },
      { id: 21, name: "MongoDB" },
      { id: 22, name: "Multitasking" },
      { id: 23, name: "MySQL" },
      { id: 24, name: "Next.js" },
      { id: 25, name: "NoSQL" },
      { id: 26, name: "Node.js" },
      { id: 27, name: "Postman API" },
      { id: 28, name: "Problem Solving" },
      { id: 29, name: "Programming" },
      { id: 30, name: "React Native" },
      { id: 31, name: "React.js" },
      { id: 32, name: "Redux.js" },
      { id: 33, name: "Report Writing" },
      { id: 34, name: "Responsive Web Design" },
      { id: 35, name: "REST APIs" },
      { id: 36, name: "Tailwind CSS" },
      { id: 37, name: "Technological Innovation" },
      { id: 38, name: "Version Control" },
    ],
  },
];
